# Generated by Django 5.0.6 on 2024-05-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_courses_rooms_groups_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_groups', to='users.rooms'),
        ),
    ]
