# Generated by Django 5.0.6 on 2024-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14)),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('lead_status', models.CharField(choices=[('lead', 'lead'), ('expectation', 'expectation'), ('set', 'set')], default='lead', max_length=100)),
            ],
        ),
    ]
