# Generated by Django 5.0.6 on 2024-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('lead', 'lead'), ('expectation', 'expectation'), ('set', 'set')], default='lead', max_length=100),
        ),
    ]
